service: flask-app

provider:
  name: aws
  runtime: python3.12
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: "{proxy+}"
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-scripts

custom:
  wsgi:
    app: run.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: true  

  scripts:
    hooks:
      "before:deploy:deploy": "python -c \"from run import create_app; create_app()\""

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: wgc-student-bucket-2

package:
  exclude:
    - node_modules/**
    - venv/**
    - .venv/**
    - tests/**